FROM amd64/node

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV NODE_ENV=production

WORKDIR /app

COPY ["sms/package.json", "sms/package-lock.json*", "./"]

RUN npm install --omit=dev

#COPY scripts/.env /src
COPY common /app/common
COPY sms/src /app/sms/src