version: '3.8'

services:
  api:
    image: car.daoyi365.com:5000/tk-api
    restart: always
    entrypoint: node /app/api/src/app.mjs
    depends_on:
      - user
      - token
    ports:
      - "9000:8080"
    volumes:
      - .env:/app/.env

  user:
    image: car.daoyi365.com:5000/tk-user
    restart: always
    entrypoint: node /app/user/src/app.mjs
    depends_on:
      - user_db
    ports:
      - "8082:8080"
    volumes:
      - .env:/app/.env

  user_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASS}
      MONGO_INITDB_AUTHENTICATION_DATABASE: ${MONGO_USER_DB}

  token:
    image: car.daoyi365.com:5000/tk-token
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
    entrypoint: node --experimental-json-modules /src/app/app.mjs
    depends_on:
      - token_cache
    ports:
      - "8084:8080"

  token_cache:
    image: redis:alpine
    restart: always