version: '3.8'

services:
  api:
    image: car.daoyi365.com:5000/tk-api
    restart: always
    entrypoint: node /app/api/src/app.mjs
    depends_on:
      - user
      - token
    ports:
      - "9000:8080"
    volumes:
      - .env:/app/.env

  user:
    image: car.daoyi365.com:5000/tk-user
    restart: always
    entrypoint: node /app/user/app.mjs
    depends_on:
      - user_db
    ports:
      - "9001:8080"
    volumes:
      - .env:/app/.env

  user_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASS}
      MONGO_INITDB_AUTHENTICATION_DATABASE: ${MONGO_USER_DB}

  token:
    image: car.daoyi365.com:5000/tk-token
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
    entrypoint: node --experimental-json-modules /app/token/app.mjs
    depends_on:
      - token_cache
    ports:
      - "9002:8080"

  token_cache:
    image: redis:alpine
    restart: always

  captcha:
    image: car.daoyi365.com:5000/tk-captcha
    restart: always
    entrypoint: node /app/captcha/app.mjs
    depends_on:
      - captcha_cache
    ports:
      - "9003:8080"

  captcha_cache:
    image: redis:alpine
    restart: always

  sms:
    image: car.daoyi365.com:5000/tk-sms
    restart: always
    entrypoint: node /app/sms/app.mjs
    depends_on:
      - sms_cache
    ports:
      - "9004:8080"
    volumes:
      - .env:/app/.env

  sms_cache:
    image: redis:alpine
    restart: always