version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: api/dockerfile
    image: car.daoyi365.com:5000/tk-api
    entrypoint: node /src/app.mjs
    depends_on:
      - user
    ports:
      - "9000:8080"
    volumes:
      - .env:/src/.env

  user:
    build:
      context: ./
      dockerfile: user/dockerfile
    image: car.daoyi365.com:5000/tk-user
    entrypoint: node --experimental-json-modules /src/app.mjs
    depends_on:
      - user_db
    ports:
      - "8082:8080"
    volumes:
      - .env:/src/.env

  user_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_USER_PASS}
      MONGO_INITDB_AUTHENTICATION_DATABASE: ${MONGO_USER_DB}

  user_migration:
    image: car.daoyi365.com:5000/tk-user
    depends_on:
      - user_db
    entrypoint: node /src/migration.mjs
    volumes:
      - .env:/src/.env

  token:
    build:
      context: ./
      dockerfile: token/dockerfile
    image: car.daoyi365.com:5000/tk-token
    environment:
      - SECRET_KEY=${SECRET_KEY}
    entrypoint: node --experimental-json-modules /src/app/app.mjs
    ports:
      - "8084:8080"

  token_cache:
    image: redis:alpine
    restart: always