FROM amd64/node

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV NODE_ENV=production

WORKDIR /app

COPY ["captcha/package.json", "captcha/package-lock.json*", "./"]

RUN npm install --omit=dev

#COPY common /app/common
COPY captcha/src /app/captcha/src