FROM amd64/node

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV NODE_ENV=production

WORKDIR /src

COPY ["token/package.json", "token/package-lock.json*", "./"]

RUN chown -R node:node /src

USER node

RUN npm install --production

COPY --chown=node:node token app