FROM golang:1.18-alpine as builder

# 设置必要的环境变量
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOPROXY=https://goproxy.cn,direct

RUN set -ex \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk --update add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apk --no-cache add ca-certificates

# 移动到工作目录：/build
WORKDIR /data

# 将代码复制到容器中
COPY . .

RUN go mod download && go mod tidy -v && go build -o apid apid.go

# 运行阶段指定scratch作为基础镜像
FROM alpine

WORKDIR /app

# 拷贝二进制可执行文件
COPY --from=builder /data/apid /app/apid

# 下载时区包
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo

# 设置当前时区
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# https ssl证书
COPY --from=builder /data/config/config.json /app/config/config.json

# 需要运行的命令
ENTRYPOINT ["./apid"]