'use strict'

const privileges = {
    admin: 0,
    user: 1,
    finance: 2,
    site: 3,
    system: 4,
}

export const privilegeSettings = [
    {url: '/backend/v1/user/:userId', method: "GET", privilege: privileges.user},
    {url: "/backend/v1/users", method: "GET", privilege: privileges.user},
    {url: "/backend/v1/user/message", method: "POST", privilege: privileges.user},
    {url: "/backend/v1/user/messages", method: "GET", privilege: privileges.user},
    {url: '/backend/v1/user/reports', method: 'GET', privilege: privileges.user},
    {url: '/backend/v1/user/level/setting', method: 'POST', privilege: privileges.user},
    {url: "/backend/v1/api/user/wallet/withdraw/audit", method: "POST", privilege: privileges.finance},
    {url: '/backend/v1/site', method: "POST", privilege: privileges.site},
    {url: '/backend/v1/sites', method: "GET", privilege: privileges.site},
    {url: "/backend/v1/site/:siteId", method: "PUT", privilege: privileges.site},
    {url: "/backend/v1/user/:userId/wallet/", method: "GET", privilege: privileges.finance},
    {url: '/backend/v1/system/settings', method: 'GET', privilege: privileges.system},
    {url: '/backend/v1/system/setting', method: 'PUT', privilege: privileges.system},
    {url: '/backend/v1/system/versions', method: 'GET', privilege: privileges.system},
    {url: '/backend/v1/system/version', method: 'POST', privilege: privileges.system},
    {url: '/backend/v1/system/version/:versionId', method: 'DELETE', privilege: privileges.system},
    {url: '/backend/v1/system/questions', method: "GET", privilege: privileges.system},
    {url: '/backend/v1/system/question/:questionId/answer', method: "GET", privilege: privileges.system},
    {url: '/backend/v1/system/question', method: "POST", privilege: privileges.system},
    {url: '/backend/v1/system/question/:questionId', method: "PUT", privilege: privileges.system},
    {url: '/backend/v1/system/question/:questionId', method: "DELETE", privilege: privileges.system},
    {url: '/backend/v1/member/items', method: 'GET', privilege: privileges.finance},
    {url: '/backend/v1/member/item/add', method: 'POST', privilege: privileges.finance},
    {url: '/backend/v1/member/item/update', method: 'POST', privilege: privileges.finance},
    {url: '/backend/v1/member/item/delete', method: 'POST', privilege: privileges.finance},
    {url: '/backend/v1/rice/items', method: 'GET', privilege: privileges.finance},
    {url: '/backend/v1/rice/item/add', method: 'POST', privilege: privileges.finance},
    {url: '/backend/v1/rice/item/update', method: 'POST', privilege: privileges.finance},
    {url: '/backend/v1/rice/item/delete', method: 'POST', privilege: privileges.finance},
    {url: "/backend/v1/api/promotion/commission/list", method: "GET", privilege: privileges.finance},
    {url: "/backend/v1/api/promotion/commission/add", method: "POST", privilege: privileges.finance},
    {url: "/backend/v1/api/promotion/commission/update", method: "POST", privilege: privileges.finance},
    {url: '/backend/v1/api/promotion/commission/delete', method: "POST", privilege: privileges.finance},
    {url: '/backend/v1/api/user/withdraw/records', method: "GET", privilege: privileges.finance},
    {url: '/backend/v1/admins/privileges', method: "GET", privilege: privileges.admin},
    {url: '/backend/v1/admin/:adminId/privileges', method: "PUT", privilege: privileges.admin},
]
