cat << EOF > .env
COMPOSE_PROJECT_NAME=tk
REGISTRY=car.daoyi365.com:5000/

MONGO_USER_HOST=user_db
MONGO_USER_DB=tkuser
MONGO_USER_USER=tkuser
MONGO_USER_PASS=tkuser

MONGO_SYSTEM_HOST=system_db
MONGO_SYSTEM_DB=tksystem
MONGO_SYSTEM_USER=tksystem
MONGO_SYSTEM_PASS=tksystem

SECRET_KEY=123456

SMSBAO_USER=111
SMSBAO_KEY=222
EOF

