cat << EOF > .env
COMPOSE_PROJECT_NAME=tk
REGISTRY=car.daoyi365.com:5000/
HOST_NAME=http://localhost:9000

MONGO_USER_HOST=user_db
MONGO_USER_DB=tkuser
MONGO_USER_USER=tkuser
MONGO_USER_PASS=tkuser

MONGO_SYSTEM_HOST=system_db
MONGO_SYSTEM_DB=tksystem
MONGO_SYSTEM_USER=tksystem
MONGO_SYSTEM_PASS=tksystem

MONGO_SITE_HOST=site_db
MONGO_SITE_DB=tksite
MONGO_SITE_USER=tksite
MONGO_SITE_PASS=tksite

MONGO_LEDGER_HOST=ledger_db
MONGO_LEDGER_DB=tkledger
MONGO_LEDGER_USER=tkledger
MONGO_LEDGER_PASS=tkledger

MONGO_PAYMENT_HOST=payment_db
MONGO_PAYMENT_DB=tkpayment
MONGO_PAYMENT_USER=tkpayment
MONGO_PAYMENT_PASS=tkpayment

MONGO_ADMIN_HOST=admin_db
MONGO_ADMIN_DB=tkadmin
MONGO_ADMIN_USER=tkadmin
MONGO_ADMIN_PASS=tkadmin

SECRET_KEY=123456

SMSBAO_USER=111
SMSBAO_KEY=222
EOF

