FROM amd64/node

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV NODE_ENV=production

WORKDIR /app

COPY ["user/package.json", "user/package-lock.json*", "./"]

RUN npm install --omit=dev

#COPY scripts/.env /src
COPY common /app/common
COPY user /app/user