FROM amd64/node

ENV NODE_ENV=production

WORKDIR /src

COPY ["user/package.json", "user/package-lock.json*", "./"]

RUN npm install --omit=dev && npm install -g nodemon

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#COPY scripts/.env /src
COPY user/*.mjs /src
