FROM amd64/node

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV NODE_ENV=production

WORKDIR /app

COPY ["api/package.json", "api/package-lock.json*", "./"]

RUN npm install --production

COPY common /app/common
COPY api/src /app/api/src

