FROM node

ENV NODE_ENV=production

WORKDIR /src

COPY ["api/package.json", "api/package-lock.json*", "./"]

RUN npm install --production

ENV TZ=Asia/Hong_Kong
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY api/node_template.json /src
COPY api/*.mjs /src

