name: Automation

on:
  push:
    branches: [ main ]

jobs:
  Automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"

      - name: test user
        run: cd user && npm install && npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Compose build
        run: sh scripts/build_all.sh

      - name: start services for integration test
        run: sh scripts/gen_integration_env.sh && sh scripts/start_for_integration.sh
      - name: integration test
        run: cd tests/integration && npm install && npm run test

      - name: show logs when failed
        if: failure()
        run: docker compose -f deploy.docker-compose.yaml logs

      - name: push image
        run: sh scripts/push_image.sh

      - name: scp files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "deploy.docker-compose.yaml, scripts/deploy.sh"
          target: "/root/tkplatform"

      - name: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd tkplatform && sh deploy.sh