name: Just test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-docker@v2

      - name: Build with Docker Compose
        run: |
          docker compose build && docker compose push