name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: ls
        uses: appleboy/ssh-action@v0.1.7
        script: |
          ls /root