name: Deployment

on:
  workflow_run:
    workflows: [ "Integration test" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: push image
        run:
          sh scripts/push_image.sh

      - name: scp files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "deploy.docker-compose.yaml, scripts/depoly.sh"
          target: "/root/tkplatform"

      - name: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd tkplatform && sh depoly.sh
