name: Integration test

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  integration-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: start services
        run:
          cd scripts && sh ./start_for_integration.sh
      - name: integration test
          cd integration && npm install && npm run test
