name: Integration test

on: [success(build)]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: start services
        run:
          cd scripts && sh ./start_for_integration.sh
      - name: integration test
          cd integration && npm install && npm run test
